"""Test Analysis Assistant MVP package."""

from .actionable_plan import (
    ActionablePlan,
    ActionableStep,
    build_plan_prompt,
    generate_actionable_plan,
)
from .analyzer import analyze_report_text
from .code_chunker import (
    CodeAwareChunker,
    CodeChunk,
    CodeLanguage,
    CodeUnit,
    detect_language,
)
from .content_detector import (
    CodeLanguage as DetectedCodeLanguage,
    ContentCategory,
    ContentDetectionResult,
    DocumentType,
    detect_code_language,
    detect_content_type,
    suggest_ingestion_strategy,
)
from .models import AnalysisResult, FailureRecord, FixSuggestion
from .prompt_strategy import (
    AnalysisPromptConfig,
    AnalysisPromptStrategy,
    FewShotExample,
    PromptStrategy,
    PromptSection,
    TEST_GAP_EXAMPLES,
    ROOT_CAUSE_EXAMPLES,
    build_adaptive_prompt,
    build_cot_prompt,
    build_fewshot_prompt,
    build_hierarchical_prompt,
    extract_structured_response,
    estimate_token_count,
    truncate_for_context,
    default_strategy,
)
from .rag_analyzer import (
    ChunkerType,
    RAGAnalyzer,
    RAGAnalysisResult,
    RetrievalInsight,
    rag_analyze,
)
from .retrieval import (
    CodeAwareIngestor,
    DummyEmbeddingProvider,
    HybridRetrievalEngine,
    IngestionRecord,
    IngestDocument,
    MultiSourceIngestor,
    RetrievalEngine,
    SourceType,
    TFIDFEmbeddingProvider,
    build_analysis_prompt,
    build_analysis_prompt_from_evidence,
    compute_enhanced_confidence,
    create_code_aware_engine,
    create_hybrid_engine,
)
from .query_reformulator import (
    ErrorCategory,
    FailureTrace,
    QueryReformulator,
    QueryVariant,
    ReformulatedQueries,
    reformulate_queries,
)
from .root_cause import (
    RootCauseAnalysis,
    RootCauseAnalyzer,
    RootCauseCategory,
    RootCauseHypothesis,
    generate_root_cause_hypotheses,
)
from .store import (
    AdaptiveConfidenceCalibrator,
    CorpusStats,
    PersistentVectorStore,
    StoredChunk,
    create_persistent_engine,
)

__all__ = [
    "analyze_report_text",
    "AnalysisResult",
    "ChunkerType",
    "FailureRecord",
    "FixSuggestion",
    "IngestionRecord",
    "IngestDocument",
    "MultiSourceIngestor",
    "RAGAnalyzer",
    "RAGAnalysisResult",
    "RetrievalInsight",
    "RetrievalEngine",
    "SourceType",
    "build_analysis_prompt",
    "build_analysis_prompt_from_evidence",
    "compute_enhanced_confidence",
    "rag_analyze",
    "HybridRetrievalEngine",
    "DummyEmbeddingProvider",
    "TFIDFEmbeddingProvider",
    "create_hybrid_engine",
    "ActionablePlan",
    "ActionableStep",
    "generate_actionable_plan",
    "build_plan_prompt",
    "CodeAwareChunker",
    "CodeChunk",
    "CodeLanguage",
    "CodeUnit",
    "detect_language",
    "CodeAwareIngestor",
    "create_code_aware_engine",
    # New store exports
    "PersistentVectorStore",
    "AdaptiveConfidenceCalibrator",
    "CorpusStats",
    "StoredChunk",
    "create_persistent_engine",
    # Root cause analysis exports
    "RootCauseAnalysis",
    "RootCauseAnalyzer",
    "RootCauseCategory",
    "RootCauseHypothesis",
    "generate_root_cause_hypotheses",
    # Query reformulation exports
    "ErrorCategory",
    "FailureTrace",
    "QueryReformulator",
    "QueryVariant",
    "ReformulatedQueries",
    "reformulate_queries",
    # Content detection exports
    "ContentCategory",
    "ContentDetectionResult",
    "DocumentType",
    "DetectedCodeLanguage",
    "detect_code_language",
    "detect_content_type",
    "suggest_ingestion_strategy",
    # Prompt strategy exports
    "PromptStrategy",
    "AnalysisPromptConfig",
    "AnalysisPromptStrategy",
    "FewShotExample",
    "PromptSection",
    "TEST_GAP_EXAMPLES",
    "ROOT_CAUSE_EXAMPLES",
    "build_adaptive_prompt",
    "build_cot_prompt",
    "build_fewshot_prompt",
    "build_hierarchical_prompt",
    "extract_structured_response",
    "estimate_token_count",
    "truncate_for_context",
    "default_strategy",
]
