"""Test Analysis Assistant MVP package."""

from .actionable_plan import (
    ActionablePlan,
    ActionableStep,
    build_plan_prompt,
    generate_actionable_plan,
)
from .analyzer import analyze_report_text
from .code_chunker import (
    ChunkingStrategy,
    CodeAwareChunker,
    CodeChunk,
    CodeLanguage,
    CodeUnit,
    TestAwareChunker,
    chunk_test_aware,
    compute_test_relevance_score,
    create_chunker,
    detect_language,
)
from .content_detector import (
    CodeLanguage as DetectedCodeLanguage,
    ContentCategory,
    ContentDetectionResult,
    DocumentType,
    detect_code_language,
    detect_content_type,
    suggest_ingestion_strategy,
)
from .confidence_analysis import (
    ConfidenceBand,
    ConfidenceInterval,
    CalibrationMetrics,
    MetaConfidenceResult,
    UncertaintyType,
    analyze_confidence,
)
from .hybrid_analyzer import (
    HybridAnalyzer,
    HybridAnalysisResult,
    HybridInsight,
    hybrid_analyze,
)
from .ingestion_pipeline import (
    IngestionHandler,
    IngestionProgress,
    PipelineConfig,
    PipelineResult,
    ProcessingResult,
    SourceConfig,
    UnifiedIngestionPipeline,
    create_unified_pipeline,
)
from .llm_integration import (
    LLMAnalyzer,
    LLMConfig,
    LLMProvider,
    LLMResponse,
    create_analyzer,
    create_llm_client,
)
from .models import AnalysisResult, FailureRecord, FixSuggestion
from .prompt_strategy import (
    AnalysisPromptConfig,
    AnalysisPromptStrategy,
    FewShotExample,
    PromptStrategy,
    PromptSection,
    TEST_GAP_EXAMPLES,
    ROOT_CAUSE_EXAMPLES,
    build_adaptive_prompt,
    build_cot_prompt,
    build_fewshot_prompt,
    build_hierarchical_prompt,
    extract_structured_response,
    estimate_token_count,
    truncate_for_context,
    default_strategy,
)
from .rag_analyzer import (
    ChunkerType,
    RAGAnalyzer,
    RAGAnalysisResult,
    RetrievalInsight,
    rag_analyze,
)
from .retrieval import (
    ArtifactBundle,
    CodeAwareIngestor,
    DummyEmbeddingProvider,
    HybridRetrievalEngine,
    IngestionRecord,
    IngestDocument,
    MultiSourceIngestor,
    RetrievalEngine,
    SentenceTransformerEmbeddingProvider,
    SourceType,
    TFIDFEmbeddingProvider,
    build_analysis_prompt,
    build_analysis_prompt_from_evidence,
    compute_enhanced_confidence,
    create_code_aware_engine,
    create_embedding_provider,
    create_hybrid_engine,
)
from .query_reformulator import (
    ErrorCategory,
    FailureTrace,
    QueryReformulator,
    QueryVariant,
    ReformulatedQueries,
    reformulate_queries,
)
from .query_understanding import (
    QueryIntent,
    IntentClassification,
    QueryUnderstanding,
    ContextualVariant,
    QueryUnderstandingEngine,
    understand_query,
)
from .root_cause import (
    RootCauseAnalysis,
    RootCauseAnalyzer,
    RootCauseCategory,
    RootCauseHypothesis,
    generate_root_cause_hypotheses,
)
from .store import (
    AdaptiveConfidenceCalibrator,
    CorpusStats,
    PersistentVectorStore,
    StoredChunk,
    create_persistent_engine,
)
from .multimodal import (
    ExtractedTable,
    ImageOCRProcessor,
    ModalityType,
    MultimodalIngestor,
    OCRResult,
    ProcessedArtifact,
    TableExtractor,
    TesseractOCRProcessor,
)

__all__ = [
    "analyze_report_text",
    "AnalysisResult",
    "ArtifactBundle",
    "ChunkerType",
    "FailureRecord",
    "FixSuggestion",
    "IngestionRecord",
    "IngestDocument",
    "MultiSourceIngestor",
    "RAGAnalyzer",
    "RAGAnalysisResult",
    "RetrievalInsight",
    "RetrievalEngine",
    "SourceType",
    "build_analysis_prompt",
    "build_analysis_prompt_from_evidence",
    "compute_enhanced_confidence",
    "rag_analyze",
    "HybridRetrievalEngine",
    "DummyEmbeddingProvider",
    "TFIDFEmbeddingProvider",
    "SentenceTransformerEmbeddingProvider",
    "create_embedding_provider",
    "create_hybrid_engine",
    "ActionablePlan",
    "ActionableStep",
    "generate_actionable_plan",
    "build_plan_prompt",
    "ChunkingStrategy",
    "CodeAwareChunker",
    "CodeChunk",
    "CodeLanguage",
    "CodeUnit",
    "TestAwareChunker",
    "chunk_test_aware",
    "compute_test_relevance_score",
    "create_chunker",
    "detect_language",
    "CodeAwareIngestor",
    "create_code_aware_engine",
    # New store exports
    "PersistentVectorStore",
    "AdaptiveConfidenceCalibrator",
    "CorpusStats",
    "StoredChunk",
    "create_persistent_engine",
    # Root cause analysis exports
    "RootCauseAnalysis",
    "RootCauseAnalyzer",
    "RootCauseCategory",
    "RootCauseHypothesis",
    "generate_root_cause_hypotheses",
    # Query reformulation exports
    "ErrorCategory",
    "FailureTrace",
    "QueryReformulator",
    "QueryVariant",
    "ReformulatedQueries",
    "reformulate_queries",
    # Query understanding exports
    "QueryIntent",
    "IntentClassification",
    "QueryUnderstanding",
    "ContextualVariant",
    "QueryUnderstandingEngine",
    "understand_query",
    # Content detection exports
    "ContentCategory",
    "ContentDetectionResult",
    "DocumentType",
    "DetectedCodeLanguage",
    "detect_code_language",
    "detect_content_type",
    "suggest_ingestion_strategy",
    # Prompt strategy exports
    "PromptStrategy",
    "AnalysisPromptConfig",
    "AnalysisPromptStrategy",
    "FewShotExample",
    "PromptSection",
    "TEST_GAP_EXAMPLES",
    "ROOT_CAUSE_EXAMPLES",
    "build_adaptive_prompt",
    "build_cot_prompt",
    "build_fewshot_prompt",
    "build_hierarchical_prompt",
    "extract_structured_response",
    "estimate_token_count",
    "truncate_for_context",
    "default_strategy",
    # Multimodal ingestion exports
    "ExtractedTable",
    "ImageOCRProcessor",
    "TesseractOCRProcessor",
    "ModalityType",
    "MultimodalIngestor",
    "OCRResult",
    "ProcessedArtifact",
    "TableExtractor",
    # Unified ingestion pipeline exports
    "IngestionHandler",
    "IngestionProgress",
    "PipelineConfig",
    "PipelineResult",
    "ProcessingResult",
    "SourceConfig",
    "UnifiedIngestionPipeline",
    "create_unified_pipeline",
    # Hybrid analyzer exports
    "HybridAnalyzer",
    "HybridAnalysisResult",
    "HybridInsight",
    "hybrid_analyze",
    # LLM integration exports
    "LLMAnalyzer",
    "LLMConfig",
    "LLMProvider",
    "LLMResponse",
    "create_analyzer",
    "create_llm_client",
]
